import { AlertTriangle, CheckCircle2, ShieldAlert, RefreshCw, Download } from 'lucide-react';
import { useVerificationStore } from '../../store/useVerificationStore';
import { motion } from 'motion/react';
import { jsPDF } from 'jspdf';


function generatePDF(result) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });

  const W = doc.internal.pageSize.getWidth();   // 210
  const margin = 16;
  const contentW = W - margin * 2;
  let y = 0;

  const isHighRisk = result.riskScore < 40;
  const isMediumRisk = result.riskScore >= 40 && result.riskScore < 70;

  const verdict = isHighRisk
    ? 'CRITICAL RISK — LIKELY A SCAM'
    : isMediumRisk
    ? 'CAUTION ADVISED — EXERCISE CARE'
    : 'LIKELY LEGITIMATE — PROCEED WITH CARE';

  const scoreHex = isHighRisk ? [239, 68, 68] : isMediumRisk ? [245, 158, 11] : [16, 185, 129];

  // ── Header banner ──────────────────────────────────────────────────────────
  doc.setFillColor(27, 18, 34);
  doc.rect(0, 0, W, 38, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(248, 244, 233);
  doc.text('OfferVerify', margin, 18);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(246, 219, 192);
  doc.text('AI-Powered Job Offer Verification Report', margin, 27);
  doc.text(`Generated: ${new Date().toLocaleString('en-IN', { dateStyle: 'long', timeStyle: 'short' })}`, margin, 33);

  y = 46;

  // ── Company + Score ────────────────────────────────────────────────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(27, 18, 34);
  doc.text(result.companyName || 'Unknown Company', margin, y);
  y += 7;

  // Verdict pill
  doc.setFillColor(...scoreHex);
  doc.roundedRect(margin, y, contentW, 12, 3, 3, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text(verdict, margin + 4, y + 8);
  y += 18;

  // Score row
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(42);
  doc.setTextColor(...scoreHex);
  doc.text(String(result.riskScore), margin, y + 10);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(100, 100, 100);
  doc.text('/ 100  TRUST SCORE', margin + 26, y + 8);

  const barX = margin;
  const barY = y + 14;
  const barH = 4;
  doc.setFillColor(220, 220, 220);
  doc.roundedRect(barX, barY, contentW, barH, 2, 2, 'F');
  doc.setFillColor(...scoreHex);
  doc.roundedRect(barX, barY, (contentW * result.riskScore) / 100, barH, 2, 2, 'F');
  y += 24;

  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, W - margin, y);
  y += 8;

  const renderSection = (title, items, colorRGB, bullet) => {
    if (!items || items.length === 0) return;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(...colorRGB);
    doc.text(title, margin, y);
    y += 6;

    items.forEach((item) => {
      // check page overflow
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      doc.setFillColor(...colorRGB.map((c) => Math.min(255, c + 180)));
      doc.roundedRect(margin, y - 4, contentW, 8, 1.5, 1.5, 'F');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(...colorRGB);
      doc.text(bullet, margin + 2, y + 1);

      doc.setFont('helvetica', 'normal');
      doc.setTextColor(40, 40, 40);
      const lines = doc.splitTextToSize(item, contentW - 10);
      doc.text(lines[0], margin + 8, y + 1);
      y += 8;

      // Extra lines of long items
      for (let i = 1; i < lines.length; i++) {
        if (y > 270) { doc.addPage(); y = 20; }
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(40, 40, 40);
        doc.text(lines[i], margin + 8, y + 1);
        y += 6;
      }
    });
    y += 4;
  };

  renderSection('⚠  Critical Red Flags', result.redFlags, [180, 40, 40], '●');
  renderSection('△  Warnings & Anomalies', result.warnings, [160, 100, 10], '▲');
  renderSection('✓  Positive Indicators', result.positives, [20, 140, 90], '✓');

  // ── Footer ─────────────────────────────────────────────────────────────────
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 160);
    doc.text(
      'This report is generated by OfferVerify AI. Always cross-verify independently.',
      margin,
      292
    );
    doc.text(`Page ${i} of ${pageCount}`, W - margin - 16, 292);
  }

  const safeName = (result.companyName || 'offer').replace(/[^a-z0-9]/gi, '_').toLowerCase();
  doc.save(`OfferVerify_${safeName}_${Date.now()}.pdf`);
}

// ─── Component ───────────────────────────────────────────────────────────────
export function ResultsDashboard() {
  const result = useVerificationStore((state) => state.result);
  const reset = useVerificationStore((state) => state.reset);

  if (!result) return null;

  const { riskScore } = result;
  const isHighRisk = riskScore < 40;
  const isMediumRisk = riskScore >= 40 && riskScore < 70;
  const isLowRisk = riskScore >= 70;

  const recommendation = isHighRisk
    ? 'Critical Risk! Likely a scam.'
    : isMediumRisk
    ? 'Caution advised.'
    : 'Likely Legitimate.';

  const scoreColor = isHighRisk
    ? 'text-red-500'
    : isMediumRisk
    ? 'text-amber-500'
    : 'text-emerald-500';

  const scoreBgColor = isHighRisk
    ? 'bg-red-500'
    : isMediumRisk
    ? 'bg-amber-500'
    : 'bg-emerald-500';

  const HeaderIcon = isHighRisk ? ShieldAlert : isMediumRisk ? AlertTriangle : CheckCircle2;
  const headerColor = isHighRisk
    ? 'text-red-500'
    : isMediumRisk
    ? 'text-amber-500'
    : 'text-emerald-500';

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className="flex-1 w-full max-w-4xl mx-auto flex flex-col p-6 sm:p-10"
    >
      {/* ── Header row ─────────────────────────────────────────────────────── */}
      <div className="flex items-center justify-between mb-8 pb-6 border-b border-white/10 gap-3 flex-wrap">
        <div className="flex items-center gap-3">
          <HeaderIcon className={`w-8 h-8 ${headerColor}`} />
          <h2 className="text-2xl font-bold text-white tracking-tight">Verification Complete</h2>
        </div>

        {/* Action buttons */}
        <div className="flex items-center gap-3 flex-wrap">
          {/* Download PDF */}
          <motion.button
            onClick={() => generatePDF(result)}
            whileHover={{ scale: 1.04 }}
            whileTap={{ scale: 0.97 }}
            className="px-4 py-2 rounded-xl font-semibold text-sm flex items-center gap-2 cursor-pointer transition-all
                       shadow-lg shadow-vd-accent/30
                       border border-vd-accent/50 hover:border-vd-accent
                       text-vd-primary"
            style={{
              background: 'linear-gradient(135deg, #935073 0%, #6b3254 100%)',
            }}
          >
            <Download className="w-4 h-4" />
            Download Report
          </motion.button>

          {/* Start Over */}
          <button
            onClick={reset}
            className="px-4 py-2 bg-white/5 border border-white/10 hover:bg-white/10 transition-colors rounded-xl font-medium text-slate-300 tracking-wide text-sm flex items-center gap-2 cursor-pointer"
          >
            <RefreshCw className="w-4 h-4" /> Start Over
          </button>
        </div>
      </div>

      {/* ── Recommendation Banner ───────────────────────────────────────────── */}
      <div
        className={`mb-8 p-4 sm:p-5 rounded-2xl border ${
          isHighRisk
            ? 'bg-red-500/10 border-red-500/30'
            : isMediumRisk
            ? 'bg-amber-500/10 border-amber-500/30'
            : 'bg-emerald-500/10 border-emerald-500/30'
        } flex items-start sm:items-center gap-4 shadow-lg`}
      >
        <div className="flex-1">
          <p className="text-white font-bold text-lg sm:text-xl tracking-tight">{recommendation}</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        {/* ── Score Card ───────────────────────────────────────────────────── */}
        <div className="md:col-span-1 border border-white/10 bg-white/5 p-6 md:p-8 rounded-3xl text-center flex flex-col items-center justify-center shadow-lg relative overflow-hidden backdrop-blur-xl">
          <div className={`absolute top-0 w-full h-1 ${scoreBgColor}`} />
          <h3 className="text-slate-400 font-semibold mb-4 uppercase tracking-widest text-xs">Trust Score</h3>
          <div className={`text-7xl font-black ${scoreColor} tracking-tighter mb-2`}>{result.riskScore}</div>
          <div className="text-slate-500 font-bold text-sm uppercase tracking-widest mb-6">out of 100</div>

          <div className="h-2 w-full bg-white/10 rounded-full overflow-hidden flex">
            <motion.div
              initial={{ width: 0 }}
              animate={{ width: `${result.riskScore}%` }}
              transition={{ duration: 1, delay: 0.5, ease: 'easeOut' }}
              className={`h-full ${scoreBgColor}`}
            />
          </div>
          <p className="text-slate-400 text-xs mt-4 font-medium uppercase tracking-widest">
            {isHighRisk ? 'Critical Danger' : isMediumRisk ? 'Exercise Caution' : 'Looks Safe'}
          </p>
        </div>

        {/* ── Detailed Analysis ────────────────────────────────────────────── */}
        <div className="md:col-span-2 space-y-6">
          {/* RED FLAGS */}
          {result.redFlags.length > 0 && (
            <div className="border border-red-500/20 bg-red-500/5 rounded-3xl p-6 shadow-lg">
              <h3 className="text-red-400 font-bold text-sm tracking-widest uppercase mb-4 flex items-center gap-2">
                <ShieldAlert className="w-4 h-4" /> Critical Red Flags
              </h3>
              <div className="space-y-3">
                {result.redFlags.map((flag, idx) => (
                  <div key={idx} className="flex gap-3 text-slate-300 text-sm bg-black/20 p-3 rounded-xl border border-red-500/10">
                    <span className="text-red-500 font-bold mt-0.5">•</span>
                    <span className="leading-relaxed">{flag}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* WARNINGS */}
          {result.warnings.length > 0 && (
            <div className="border border-amber-500/20 bg-amber-500/5 rounded-3xl p-6 shadow-lg">
              <h3 className="text-amber-400 font-bold text-sm tracking-widest uppercase mb-4 flex items-center gap-2">
                <AlertTriangle className="w-4 h-4" /> Warnings & Anomalies
              </h3>
              <div className="space-y-3">
                {result.warnings.map((warning, idx) => (
                  <div key={idx} className="flex gap-3 text-slate-300 text-sm bg-black/20 p-3 rounded-xl border border-amber-500/10">
                    <span className="text-amber-500 font-bold mt-0.5">•</span>
                    <span className="leading-relaxed">{warning}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* POSITIVES */}
          {result.positives.length > 0 && (
            <div className="border border-emerald-500/20 bg-emerald-500/5 rounded-3xl p-6 shadow-lg">
              <h3 className="text-emerald-400 font-bold text-sm tracking-widest uppercase mb-4 flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4" /> Positive Signs
              </h3>
              <div className="space-y-3">
                {result.positives.map((positive, idx) => (
                  <div key={idx} className="flex gap-3 text-slate-300 text-sm bg-black/20 p-3 rounded-xl border border-emerald-500/10">
                    <span className="text-emerald-500 font-bold mt-0.5">✓</span>
                    <span className="leading-relaxed">{positive}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </motion.div>
  );
}
